Workaround for setuptools install_requires bug with pyasn1
When installing service_identity with `setup.py install` the order of
the install_requires directive causes setuptools to fail to install
`pyasn1` with the following error message:

    error: The 'pyasn1' distribution was not found and is required by service-identity

The workaround is to switch the order of `pyasn1` and `pyasn1-modules` in
the install_requires directive.

Setuptools issue: https://github.com/pypa/setuptools/issues/498